// <auto-generated />
using ImobPlus.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImobPlus.Migrations
{
    [DbContext(typeof(ImobDbContext))]
    [Migration("20201116091336_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImobPlus.Models.Conseiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apropos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIsponible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPrenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conseillers");
                });

            modelBuilder.Entity("ImobPlus.Models.Construire", b =>
                {
                    b.Property<int>("MyProperty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailConst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuConst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageConst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameConst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeConst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MyProperty");

                    b.ToTable("Construires");
                });

            modelBuilder.Entity("ImobPlus.Models.ContactPro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bailleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPros");
                });

            modelBuilder.Entity("ImobPlus.Models.Contacts", b =>
                {
                    b.Property<int>("Id_Contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPrenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precoccupation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Contact");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ImobPlus.Models.Demenagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinaDem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuDepartDem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessagDem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameDem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Demenagements");
                });

            modelBuilder.Entity("ImobPlus.Models.Investir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailInvest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageInvest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInvest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeInvest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Investirs");
                });

            modelBuilder.Entity("ImobPlus.Models.Liconseil", b =>
                {
                    b.Property<int>("Id_Liconseil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPrenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Liconseil");

                    b.ToTable("Liconseils");
                });

            modelBuilder.Entity("ImobPlus.Models.Post", b =>
                {
                    b.Property<int>("Id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Choix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Bailleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_Bailleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mini_Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Bailleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nbre_Chambres")
                        .HasColumnType("int");

                    b.Property<int>("nbre_Cuisines")
                        .HasColumnType("int");

                    b.Property<int>("nbre_Douches")
                        .HasColumnType("int");

                    b.HasKey("Id_Post");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
